
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fpga_game(

    //////////// CLOCK //////////
    input        CLOCK2_50,
    input        CLOCK3_50,
    input        CLOCK4_50,
    input        CLOCK_50,

    //////////// SEG7 //////////
    output [6:0] HEX0,
    output [6:0] HEX1,
    output [6:0] HEX2,
    output [6:0] HEX3,
    output [6:0] HEX4,
    output [6:0] HEX5,

    //////////// KEY //////////
    input [3:0]  KEY,

    //////////// LED //////////
    output [9:0] LEDR,

    //////////// SW //////////
    input [9:0]  SW,

    //////////// VGA //////////
    output       VGA_BLANK_N,
    output [7:0] VGA_B,
    output       VGA_CLK,
    output [7:0] VGA_G,
    output       VGA_HS,
    output [7:0] VGA_R,
    output       VGA_SYNC_N,
    output       VGA_VS
);

   localparam                   ENEMY_STATE_WIDTH = 19;
   localparam                   SPACESHIP_STATE_WIDTH = 28;
   localparam                   GAME_STATE_WIDTH = ENEMY_STATE_WIDTH*8 + SPACESHIP_STATE_WIDTH;

   wire [9:0]                   x;
   wire [9:0]                   y;

   wire [7:0]                   R;
   wire [7:0]                   G;
   wire [7:0]                   B;

   wire                         fire;
   wire                         change_mode;
   wire                         rotate;
   wire                         rotate_right;

   wire [GAME_STATE_WIDTH - 1:0] game_state_data;
   reg [GAME_STATE_WIDTH - 1:0]  game_state;

   wire [15:0]                   angles_hit;

   wire                          new_frame;

   always @(posedge new_frame) begin
      game_state <= game_state_data;
   end

   wire [3:0]                   enemy_count;
   wire                         collision;

   wire [9:0]                   score;

   // 0: start screen
   // 1: game screen
   // 2: game over screen
   reg [1:0]                    state;

   wire                         start_screen;
   wire                         game_screen;
   wire                         game_over_screen;

   assign start_screen = state == 2'd0;
   assign game_screen = state == 2'd1;
   assign game_over_screen = state == 2'd2;

   initial state = 2'd0;

   always @(posedge CLOCK_50) begin
      if (fire & start_screen) begin
         state <= 2'd1;
      end else if (collision & game_screen) begin
         state <= 2'd2;
      end
   end

   vga_controller vga_inst(.clk(CLOCK_50),

                           .VGA_BLANK_N(VGA_BLANK_N),
                           .VGA_B(VGA_B),
                           .VGA_CLK(VGA_CLK),
                           .VGA_G(VGA_G),
                           .VGA_HS(VGA_HS),
                           .VGA_R(VGA_R),
                           .VGA_SYNC_N(VGA_SYNC_N),
                           .VGA_VS(VGA_VS),

                           .x(x),
                           .y(y),

                           .new_frame(new_frame),

                           .R(R),
                           .G(G),
                           .B(B));

   renderer renderer_inst(.x(x),
                          .y(y),

                          .game_state(game_state),
                          .angles_hit(angles_hit),
                          .screen_state(state),

                          .R(R),
                          .G(G),
                          .B(B));

   game game_inst(.clk(CLOCK_50 & game_screen),

                  .fire(fire),
                  .change_mode(change_mode),
                  .rotate(rotate),
                  .rotate_right(rotate_right),

                  .score(score),

                  .state(game_state_data),
                  .enemy_count(enemy_count),
                  .collision(collision),
                  .angles_hit(angles_hit));

   input_controller input_inst(.clk(CLOCK_50),

                               .SW(SW),
                               .KEY(KEY),

                               .fire(fire),
                               .change_mode(change_mode),
                               .rotate(rotate),
                               .rotate_right(rotate_right));

   fpga_display disp_inst(.state(game_state),
                          .enemy_count(enemy_count),
                          .score(score),
                          .collision(collision),

                          .HEX0(HEX0),
                          .HEX1(HEX1),
                          .HEX2(HEX2),
                          .HEX3(HEX3),
                          .HEX4(HEX4),
                          .HEX5(HEX5),

                          .LEDR(LEDR));

endmodule
